name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
 BAR_CREATION: /opt/ace-11.0.0.7/tools/mqsicreatebar
 BAR_STORE: /home/bandaru/Templates
 NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
 NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }} 
 NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_REPOSITORY_URL }}

 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Bar File Creation
        run: $BAR_CREATION -data /root -b $BAR_STORE/Rest_Api_Application_Put_Get.bar -a Rest_Api_Application_Put_Get
      - name: SonarQube_Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}											
          login: ${{ secrets.SONARQUBE_TOKEN }}       
          projectBaseDir: "Rest_Api_Application_Put_Get"
          projectKey: "GWFA"
          projectName: "GWFA"
          projectVersion: "v0.0.1"
      - name: Publishing_Artifacts
        run:  curl -v -u$NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file Rest_Api_Application_Put_Get.bar  $NEXUS_REPOSITORY_URL     
      
